services:
  - type: web
    name: ideal-fit-app1
    env: node
    plan: free
    rootDir: ideal-fit
    buildCommand: echo "=== BUILD COMMAND START ===" && pwd && ls -la && npm install && mkdir -p data && npm run setup && npm run build && echo "=== BUILD COMPLETE ===" && ls -la && find . -name "build" -type d
    startCommand: node build/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./data/prod.sqlite
      - key: SHOPIFY_API_KEY
        value: df65d05c59fdde03db6cad23f63bb6e7
      - key: SCOPES
        value: write_products,read_products,read_orders,read_customers
      - key: SHOPIFY_APP_URL
        value: https://ideal-fit-app1.onrender.com
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_STORE
        sync: false
    healthCheckPath: /