services:
  - type: web
    name: ideal-fit-app
    env: node
    plan: free
    rootDir: ideal-fit
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: write_products,read_products,read_orders,read_customers
    healthCheckPath: /